{{.Metadata.Header}}

set -goq @theme-clock-mode-colour {{.ClockMode.Colour}}
set -goq @theme-display-panes-colour {{.DisplayPanes.Colour}}
set -goq @theme-display-panes-colour {{.DisplayPanesActive.Colour}}
set -goq @theme-clock-mode-style {{.ClockMode.Style}}
set -goq @theme-message-bg {{.Message.Style.Bg}}
set -goq @theme-message-command-bg {{.MessageCommand.Style.Bg}}
set -goq @theme-message-command-fg {{.MessageCommand.Style.Fg}}
set -goq @theme-message-fg {{.Message.Style.Fg}}
set -goq @theme-mode-bg {{.Mode.Style.Bg}}
set -goq @theme-mode-fg {{.Mode.Style.Fg}}
set -goq @theme-pane-active-border-bg {{.PaneActiveBorder.Style.Bg}}
set -goq @theme-pane-active-border-fg {{.PaneActiveBorder.Style.Fg}}
set -goq @theme-pane-border-bg {{.PaneBorder.Style.Bg}}
set -goq @theme-pane-border-fg {{.PaneBorder.Style.Fg}}
set -goq @theme-status-bg {{.Status.Style.Bg}}
set -goq @theme-status-fg {{.Status.Style.Fg}}
set -goq @theme-status-interval {{.Status.Interval}}
set -goq @theme-status-justify {{.Status.Justify}}
set -goq @theme-status-left-bg {{.StatusLeft.Style.Bg}}
set -goq @theme-status-left-fg {{.StatusLeft.Style.Fg}}
set -goq @theme-status-left-format "{{.StatusLeft.Format}}"
set -goq @theme-status-left-length {{.StatusLeft.Length}}
set -goq @theme-status-right-bg {{.StatusRight.Style.Bg}}
set -goq @theme-status-right-fg {{.StatusRight.Style.Fg}}
set -goq @theme-status-right-format "{{.StatusRight.Format}}"
set -goq @theme-status-right-length {{.StatusRight.Length}}
set -goq @theme-winow-status-activity-bg {{.WindowStatusActivity.Style.Bg}}
set -goq @theme-winow-status-activity-fg {{.WindowStatusActivity.Style.Fg}}
set -goq @theme-winow-status-current-bg {{.WindowStatusCurrent.Style.Bg}}
set -goq @theme-winow-status-current-fg {{.WindowStatusCurrent.Style.Fg}}
set -goq @theme-winow-status-current-format "{{.WindowStatusCurrent.Format}}"
set -goq @theme-winow-status-format "{{.WindowStatus.Format}}"
set -goq @theme-winow-status-separator "{{.WindowStatus.Separator}}"
